<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <!-- Ignore warnings to leave the Discord Game SDK unchanged. -->
    <NoWarn>CS8600,CS8601,CS8602,CS8605,CS8618,CS8625</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ContentWithTargetPath Include="lib/x86_64/discord_game_sdk.so">
      <TargetPath>discord_game_sdk.so</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </ContentWithTargetPath>
  </ItemGroup>

</Project>
